GET http://localhost:8000/categories/

###

GET http://localhost:8000/categories/id
content-type: application/json

{
    "id":49
}

###
POST http://localhost:8000/categories/
content-type: application/json

{
    "name":"technossslogy3",
    "slug": "techdsadas",
    "imageUrl":""
}

###

DELETE http://localhost:8000/categories/
content-type: application/json

{
    "id":"50"
}


###

PUT http://localhost:8000/categories/
content-type: application/json

{
    "id":"49",
    "name":"ohoho",
    "slug": "koko",
    "imageUrl":""
}

# huselt bolgoniig dund ni ### zaaglah ystoi  baidg