
###CATEGORY###
GET http://localhost:8000/categories/

###

GET http://localhost:8000/categories/ifj-hINERlnhhiMXLZ0kC
content-type: application/json

{
    "id":"ke9lkYzuq9JdHisP9vYIh"
}

###
POST http://localhost:8000/categories
content-type: application/json

{
    
    "name":"fgddrftghjfghb",
    "slug":"fgdfghfghjmjb",
    "productCount":1232
}

###

DELETE http://localhost:8000/categories/null



###

PUT http://localhost:8000/categories/ifj-hINERlnhhiMXLZ0kC
content-type: application/json

{

    "name":"dfjh",
    "slug":"esrdfg",
    "productCount":""
}


###

# PRODUCT #
###
GET http://localhost:8000/product/

###

GET http://localhost:8000/product/5wrgGy4ijBG-eBdHkpr8k



###
POST http://localhost:8000/product/
content-type: application/json

{
    "name":"toto",
    "slug":"dodo",
    "description":"baba",
    "imageUrl":"",
    "text":"hoho",
    "price":120100
}

###

PUT http://localhost:8000/product/5wrgGy4ijBG-eBdHkpr8k
content-type: application/json

{
    "name":"koko",
    "slug":"kaka",
    "description":"daadsa",
    "imageUrl":"",
    "text":"hoho",
    "price":122100
}
###

DELETE http://localhost:8000/product/tFyzX9h_Axs6XkrdcFjBO


###


###USERS
GET http://localhost:8000/users

###
POST http://localhost:8000/users
content-type: application/json

{
    "firstName":"dolasoo",
    "lastName": "xurgaasa",
    "birthDate" : "1996-07-17",
    "email": "temuulen.m@pinessc.mn",
    "phone": "966674123",
    "password": "",
    "imageUrl": ""
}

###
PUT http://localhost:8000/users/5eABI0j5UOYBbhX8Nd2KS
content-type: application/json

{
   
    "firstName":"narhan",
    "lastName": "sarhan",
    "birthDate" : "1999-07-18",
    "email": "temuulen.m@66.mn",
    "phone": "96667477",
    "password": "",
    "imageUrl": "",
    "id":"5eABI0j5UOYBbhX8Nd2KS"
}
###
GET http://localhost:8000/users/exsJchCz5wSs2CNY8j6dX


###
DELETE http://localhost:8000/users/ImYsXZe3m4xZkxLYJbieC

###

# huselt bolgoniig dund ni ### zaaglah ystoi  baidg